apiVersion: v1
kind: Service
metadata:
  name: todoapp-frontend-svc
  namespace: todo-project
spec:
  type: ClusterIP
  selector:
    app: todoapp-frontend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
