apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: milai0/pingpong-app:10.96
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-cm
                key: postgres-host
          - name: POSTGRES_DBNAME
            valueFrom:
              configMapKeyRef:
                name: postgres-cm
                key: postgres-dbname
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"