apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-backend-dep
  namespace: todo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp-backend
  template:
    metadata:
      labels:
        app: todoapp-backend
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: file-claim
      containers:
        - name: todoapp-backend
          image: milai0/todoapp-backend:15.0
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-image