apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: applications
spec:
  type: NodePort
  selector:
    app: pingpong
  ports:
    - name: http
      protocol: TCP
      port: 2346
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: milai0/pingpong-app:12.0
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /health
              port: 3001
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: db-cm
                key: db-host
          - name: POSTGRES_DBNAME
            valueFrom:
              configMapKeyRef:
                name: db-cm
                key: db-name
          resources:
            limits:
              memory: "100Mi"
              cpu: "200m"