apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: milai0/pingpong-app:8.0