apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: file-claim
      containers:
        - name: todoapp
          image: milai0/todo-app:15.0
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-image