apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: FRONTEND_IMAGE
    newName: milai0/todoapp-frontend:11.0
  - name: BACKEND_IMAGE
    newName: milai0/todoapp-backend:17.0
resources:
  - manifests/db/configuration.yaml
  - manifests/todoapp/frontend-configuration.yaml
  - manifests/todoapp/backend-configuration.yaml