apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: todo-project
data:
    db-user: ENC[AES256_GCM,data:/peNG3BVUZeC2H1v,iv:QW3BmKgTwkINn0bA66L56O16btIIlKCJNcv9tVdlDuk=,tag:uLyGSl1UkPSK/l1BNIuqbQ==,type:str]
    db-password: ENC[AES256_GCM,data:WFahmui/S9HvaZG4,iv:jqY3K72Vsd1/n7GiID5REzh1dn61Y7vqt0Wlz4nHokU=,tag:2QGQ3ynY+xXpIsHeTINrtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tz6rx2lh3s6q9qwp2zzq5nvvcd2slw5c293f986d85mh59c9nqaq36ww3h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVUh5bS9Ub05mY1pORk5a
            a0FzL2Y4ZWlPQXlvQlhxZW96V24xeFBhTmlVCllLQ0pmemg5SmxmT050L2RBdVFY
            YVN0YlA2RmpFODh6ZGQ4ZWdGYVZybUEKLS0tIFk0MWJnZE5zSXFPaEx5ZDV6bjNw
            UFdNY0hXMWZINDBCbHMreXJ5dGFNY3MK44QFwXed9O1DEzh3JjdMSiQHTNeW/HGo
            SxSq9a52qdLGX+UZzdga/ts3uhEdLFgc5wJmhO4uvmCPSikRjj2i6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-14T12:02:24Z"
    mac: ENC[AES256_GCM,data:cp0h2nCh+kAD2Au7ye60dNH0EuceJwtHHBuZkdXlbXH6DqVKswijya0wvU0mp739PIVntMrdwcQ4ctX4l3Iw4V0BKfdAGOBexoky9Ec30aTbtt1vldiyZv6CGtqTXqyfRMktEJUbEYnC9vcvQTEADU6va48RlAEo3Xq334jknjk=,iv:t0cV8blMpdX48e4DqK+0vjuPhHq48p0fE+n171conuY=,tag:5hRBu6Gt2g9P2xXequgTdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
