apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-ss
  namespace: todo-project
spec:
  serviceName: db-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgresapp
  template:
    metadata:
      labels:
        app: postgresapp
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: db-cm
                key: db-host
          - name: POSTGRES_DBNAME
            valueFrom:
              configMapKeyRef:
                name: db-cm
                key: db-dbname
          ports:
            - name: web
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi