apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-backend-dep
  namespace: todo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp-backend
  template:
    metadata:
      labels:
        app: todoapp-backend
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: file-claim
      containers:
        - name: todoapp-backend
          image: milai0/todoapp-backend:16.3
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: db-cm
                key: db-host
          - name: POSTGRES_DBNAME
            valueFrom:
              configMapKeyRef:
                name: db-cm
                key: db-dbname
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-image