apiVersion: v1
kind: Service
metadata:
  name: todoapp-backend-svc
  namespace: todo-project
spec:
  type: ClusterIP
  selector:
    app: todoapp-backend
  ports:
    - name: http
      protocol: TCP
      port: 2346
      targetPort: 3000
